services:
  server:
    build: ./server
    container_name: smartAid_server
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: smartAid_db
    restart: always
    environment:
      POSTGRES_DB: smartAid_db
      POSTGRES_USER: smartAid_user
      POSTGRES_PASSWORD: smartAid_123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smartAid_user -d smartAid_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: smartAid_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@smartaid.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5051:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
  pgadmin_data:
